# Generated by Django 3.2.6 on 2022-06-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='geo_api.provider'),
        ),
    ]
